FORMAT: 1A
HOST: http://localhost:3000

# DEMO API 文件

## 筆記
- 運行: `aglio -i demo.apib -s`
- 編譯: `aglio -i demo.apib -o demo.html`

## 更新紀錄
- 2022/03/29 v1.0.0
- 2022/03/30 修正錯字 v1.1.1

# Group 使用者權限
<!-- include(users.md) -->

# Group 報表相關
<!-- include(report.md) -->